version: "3"
services:
  filebeat:
    user: root
    image: docker.elastic.co/beats/filebeat:7.17.11
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./registry:/usr/share/filebeat/data/registry
    environment:
      - ELASTICSEARCH_HOST=${ENV_ELASTICSEARCH_URL}
      - SERVICE_NAME=${ENV_SERVICE_NAME}
