version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "${ENV_HOST_ADDR}:9200:9200"
      - "${ENV_HOST_ADDR}:9300:9300"
    networks:
      - elastic-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.11
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "${ENV_HOST_ADDR}:5601:5601"
    networks:
      - elastic-net

networks:
  elastic-net:
    driver: bridge
