services:
  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - opendistro_security.disabled=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "${ENV_HOST_ADDR}:9200:9200"
      - "${ENV_HOST_ADDR}:9300:9300"
    networks:
      - elastic-net
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: 3

  kibana:
    build:
      context: ./kibana
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=${ENV_ELASTICSEARCH_URL}
      - ELASTICSEARCH_URL=${ENV_ELASTICSEARCH_URL}
    ports:
      - "${ENV_HOST_ADDR}:5601:5601"
    networks:
      - elastic-net
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: 3

networks:
  elastic-net:
    driver: bridge
